In [1]:
w1,w2,w3 = 0.3,0.2,0.5

In [2]:
kanto = [73,67,43]
johto = [91,88,64]
hoenn = [87,134,58]
sinnoh = [102,43,37]
unova = [69,96,70]

In [3]:
weights = [w1,w2,w3]

In [4]:
def crop_yeild(region,weights):
    result = 0
    for x,y in zip(region,weights):
        result += x*y
    return result

In [5]:
crop_yeild(kanto,weights)

56.8

In [6]:
crop_yeild(johto,weights)

76.9

In [7]:
crop_yeild(hoenn,weights)

81.9

# going from list to numpy

In [8]:
import numpy as np

In [9]:
kanto = np.array([73,67,43])

In [10]:
weights = np.array([w1,w2,w3])

In [11]:
np.dot(kanto,weights)

56.8

In [12]:
(kanto*weights).sum()      #second way

56.8

In [13]:
#numpy efficiency

In [34]:
arr1 = list(range(1000))
arr2 = list(range (1000,2000))

#numpy array
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [35]:
%%time
result = 0
for x1 , x2 in zip(arr1,arr2):
    result = result+ x1*x2
result

Wall time: 0 ns


832333500

In [36]:
%%time
np.dot(arr1_np, arr2_np)

Wall time: 0 ns


832333500

In [37]:
#multi-dimentional array

In [38]:
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])

In [39]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [40]:
# 3D array 
arr3 = np.array([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.5]]])

In [41]:
np.matmul(climate_data,weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [42]:
np.dot(climate_data,weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [43]:
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [44]:
import urllib.request

urllib.request.urlretrieve('https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x2219861c220>)

In [45]:
climate_data1= np.genfromtxt('climate.txt',delimiter= ',',skip_header=1)  #delimiter is used to seperate data, here by using ","

In [46]:
weights 

array([0.3, 0.2, 0.5])

In [47]:
yeilds = climate_data1 @ weights

In [48]:
yeilds

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [49]:
#to add yeild data back to the table

In [54]:
climate_result = np.concatenate((climate_data1,yeilds.reshape(10000,1)),axis=1)

In [55]:
climate_result

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [59]:
np.savetxt('climate_result.txt',
          climate_result,fmt='%.2f', header='temp,rainfall,humidity,yeild_apples')

Numpy provides hundreds of functions for performing operations on arrays. Here are some commonly used functions:


* Mathematics: `np.sum`, `np.exp`, `np.round`, arithemtic operators 
* Array manipulation: `np.reshape`, `np.stack`, `np.concatenate`, `np.split`
* Linear Algebra: `np.matmul`, `np.dot`, `np.transpose`, `np.eigvals`
* Statistics: `np.mean`, `np.median`, `np.std`, `np.max`

> **How to find the function you need?** The easiest way to find the right function for a specific operation or use-case is to do a web search. For instance, searching for "How to join numpy arrays" leads to [this tutorial on array concatenation](https://cmdlinetips.com/2018/04/how-to-concatenate-arrays-in-numpy/). 

You can find a full list of array functions here: https://numpy.org/doc/stable/reference/routines.html

In [61]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [62]:
arr3 = np.array([[11, 12, 13, 14], 
                 [15, 16, 17, 18], 
                 [19, 11, 12, 13]])

In [63]:
arr2 + arr3

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 12, 14, 16]])

In [64]:
#adding a scalar
arr2 + 3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  4,  5,  6]])

In [65]:
arr3 - arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [66]:
arr2/2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 0.5, 1. , 1.5]])

In [67]:
arr2%2

array([[1, 0, 1, 0],
       [1, 0, 1, 0],
       [1, 1, 0, 1]], dtype=int32)

In [68]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [69]:
arr4 = ([4,5,6,7])  
#Broadcasting only works if one of the arrays can be replicated to match the other array's shape.

In [70]:
arr2 + arr4

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

In [71]:
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[2, 2, 3], [1, 2, 5]])

In [72]:
arr1 == arr2

array([[False,  True,  True],
       [False, False,  True]])

In [73]:
arr1 <= arr2

array([[ True,  True,  True],
       [False, False,  True]])

In [74]:
arr1 >= arr2

array([[False,  True,  True],
       [ True,  True,  True]])

# Array indexing

In [75]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

In [77]:
arr3.shape

(3, 2, 4)

In [78]:
arr3[1]   #0,1,2

array([[15., 16., 17., 21.],
       [63., 92., 36., 18.]])

In [79]:
arr3[1,1]

array([63., 92., 36., 18.])

In [80]:
#single element
arr3[1,1,2]

36.0

In [81]:
arr3

array([[[11. , 12. , 13. , 14. ],
        [13. , 14. , 15. , 19. ]],

       [[15. , 16. , 17. , 21. ],
        [63. , 92. , 36. , 18. ]],

       [[98. , 32. , 81. , 23. ],
        [17. , 18. , 19.5, 43. ]]])

In [82]:
#sub array

In [83]:
arr3[1:]

array([[[15. , 16. , 17. , 21. ],
        [63. , 92. , 36. , 18. ]],

       [[98. , 32. , 81. , 23. ],
        [17. , 18. , 19.5, 43. ]]])

In [84]:
arr3[1:,0:1]

array([[[15., 16., 17., 21.]],

       [[98., 32., 81., 23.]]])

In [85]:
arr3[1:,0:1,:2]

array([[[15., 16.]],

       [[98., 32.]]])

# other ways of creating numpy array

In [86]:
#All zeros
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [87]:
#all ones
np.ones((3,2,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [89]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [90]:
#random matrix
np.random.rand(2,3)   #rand gives value between 0-1

array([[0.25954299, 0.01263441, 0.9708002 ],
       [0.96190482, 0.46054336, 0.04325473]])

In [91]:
np.random.randn(2,3)

array([[-1.92828078, -2.44168826, -1.89607259],
       [-0.20131511, -1.56607773,  1.1300661 ]])

In [92]:
#fixed value
np.full([2,3],50)

array([[50, 50, 50],
       [50, 50, 50]])

In [93]:
#range with start stop and step
np.arange(10,40,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [96]:
np.arange(10,40,2).shape

(15,)

In [95]:
np.arange(10,40,2).reshape(5,3)

array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26],
       [28, 30, 32],
       [34, 36, 38]])

In [97]:
#equally spaced number in a range
np.linspace(3,10,5)

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])